- type: replace
  path: /instance_groups/name=windows-worker/jobs/name=kubelet-windows/properties/cloud-provider?
  value: vsphere

- type: replace
  path: /instance_groups/name=windows-worker/jobs/name=kube-proxy-windows/properties/cloud-provider?
  value: vsphere

